/**
 * Local catalog metadata for scenarios (SC01..SC40 and SYS_* intents).
 * Matches official case_2/voice_router_dataset/scenarios.json.
 * Used by frontend to enrich TurnResponse which only delivers scenario IDs.
 */

export const SCENARIO_CATALOG = {
  SC01: {
    id: "SC01",
    slug: "ogpo_quote",
    name: "Расчёт стоимости ОГПО",
    nameKk: "ОГПО құнын есептеу",
    nameEn: "OGPO price quote",
    domain: "auto",
    category: "sales",
    priority: "normal",
  },
  SC02: {
    id: "SC02",
    slug: "ogpo_buy",
    name: "Покупка ОГПО",
    nameKk: "ОГПО сатып алу",
    nameEn: "OGPO purchase",
    domain: "auto",
    category: "sales",
    priority: "normal",
  },
  SC03: {
    id: "SC03",
    slug: "casco_quote",
    name: "Консультация и расчёт КАСКО",
    nameKk: "КАСКО бойынша кеңес және есептеу",
    nameEn: "CASCO consultation and quote",
    domain: "auto",
    category: "sales",
    priority: "normal",
  },
  SC04: {
    id: "SC04",
    slug: "policy_add_driver",
    name: "Добавление водителя в полис",
    nameKk: "Полиске жүргізушіні қосу",
    nameEn: "Add driver to motor policy",
    domain: "auto",
    category: "servicing",
    priority: "normal",
  },
  SC05: {
    id: "SC05",
    slug: "policy_change_vehicle",
    name: "Изменение авто или госномера в полисе",
    nameKk: "Полистегі көлікті немесе нөмірді өзгерту",
    nameEn: "Change vehicle or plate in policy",
    domain: "auto",
    category: "servicing",
    priority: "normal",
  },
  SC06: {
    id: "SC06",
    slug: "travel_buy",
    name: "Покупка страховки для путешествий",
    nameKk: "Саяхат сақтандыруын сатып алу",
    nameEn: "Travel insurance purchase",
    domain: "travel",
    category: "sales",
    priority: "normal",
  },
  SC07: {
    id: "SC07",
    slug: "property_quote",
    name: "Консультация по страхованию жилья",
    nameKk: "Баспананы сақтандыру кеңесі",
    nameEn: "Home insurance consultation",
    domain: "property",
    category: "sales",
    priority: "normal",
  },
  SC08: {
    id: "SC08",
    slug: "accident_quote",
    name: "Консультация по страхованию от несчастных случаев",
    nameKk: "Жазатайым оқиғадан сақтандыру кеңесі",
    nameEn: "Accident insurance consultation",
    domain: "accident",
    category: "sales",
    priority: "normal",
  },
  SC09: {
    id: "SC09",
    slug: "dms_individual_quote",
    name: "Консультация по индивидуальному ДМС",
    nameKk: "Жеке ЕМС (ДМС) бойынша кеңес",
    nameEn: "Individual health insurance consultation",
    domain: "health",
    category: "sales",
    priority: "normal",
  },
  SC10: {
    id: "SC10",
    slug: "corporate_request",
    name: "Запрос по корпоративному страхованию",
    nameKk: "Корпоративтік сақтандыру сұрауы",
    nameEn: "Corporate insurance request",
    domain: "corporate",
    category: "sales",
    priority: "normal",
  },
  SC11: {
    id: "SC11",
    slug: "road_accident_now",
    name: "ДТП произошло только что",
    nameKk: "Жол апаты жаңа ғана болды",
    nameEn: "Road accident just happened",
    domain: "auto",
    category: "claims",
    priority: "urgent",
  },
  SC12: {
    id: "SC12",
    slug: "ogpo_victim_claim",
    name: "Обращение пострадавшего по ОГПО виновника",
    nameKk: "Кінәлінің ОГПО-сы бойынша жәбірленушінің өтініші",
    nameEn: "Claim as victim under culprit's OGPO",
    domain: "auto",
    category: "claims",
    priority: "high",
  },
  SC13: {
    id: "SC13",
    slug: "casco_claim",
    name: "Заявление об ущербе по КАСКО",
    nameKk: "КАСКО бойынша залал туралы өтініш",
    nameEn: "CASCO damage claim",
    domain: "auto",
    category: "claims",
    priority: "high",
  },
  SC14: {
    id: "SC14",
    slug: "property_claim",
    name: "Заявление об ущербе имуществу",
    nameKk: "Мүлік залалы туралы өтініш",
    nameEn: "Property damage claim",
    domain: "property",
    category: "claims",
    priority: "high",
  },
  SC15: {
    id: "SC15",
    slug: "travel_claim_abroad",
    name: "Медицинский случай за границей",
    nameKk: "Шетелдегі медициналық жағдай",
    nameEn: "Medical event abroad",
    domain: "travel",
    category: "claims",
    priority: "urgent",
  },
  SC16: {
    id: "SC16",
    slug: "accident_claim",
    name: "Заявление о травме / несчастном случае",
    nameKk: "Жарақат / жазатайым оқиға туралы өтініш",
    nameEn: "Accident injury claim",
    domain: "accident",
    category: "claims",
    priority: "high",
  },
  SC17: {
    id: "SC17",
    slug: "claim_status",
    name: "Статус страхового случая",
    nameKk: "Сақтандыру жағдайының мәртебесі",
    nameEn: "Claim status",
    domain: "general",
    category: "claims",
    priority: "normal",
  },
  SC18: {
    id: "SC18",
    slug: "claim_documents",
    name: "Документы для страхового случая",
    nameKk: "Сақтандыру жағдайы үшін құжаттар",
    nameEn: "Documents for a claim",
    domain: "general",
    category: "claims",
    priority: "normal",
  },
  SC19: {
    id: "SC19",
    slug: "claim_dispute",
    name: "Несогласие с решением по случаю",
    nameKk: "Сақтандыру шешімімен келіспеу",
    nameEn: "Disagreement with claim decision",
    domain: "general",
    category: "claims",
    priority: "high",
  },
  SC20: {
    id: "SC20",
    slug: "damage_inspection",
    name: "Запись на осмотр автомобиля",
    nameKk: "Көлікті қарап тексеруге жазылу",
    nameEn: "Book vehicle inspection",
    domain: "auto",
    category: "claims",
    priority: "normal",
  },
  SC21: {
    id: "SC21",
    slug: "dms_appointment",
    name: "Запись к врачу по ДМС",
    nameKk: "ЕМС бойынша дәрігерге жазылу",
    nameEn: "Doctor appointment under DMS",
    domain: "health",
    category: "servicing",
    priority: "normal",
  },
  SC22: {
    id: "SC22",
    slug: "dms_coverage",
    name: "Проверка покрытия по ДМС",
    nameKk: "ЕМС қамтуын тексеру",
    nameEn: "DMS coverage check",
    domain: "health",
    category: "servicing",
    priority: "normal",
  },
  SC23: {
    id: "SC23",
    slug: "dms_clinics",
    name: "Список партнёрских клиник",
    nameKk: "Серіктес емханалар тізімі",
    nameEn: "Partner clinics list",
    domain: "health",
    category: "info",
    priority: "normal",
  },
  SC24: {
    id: "SC24",
    slug: "dms_card",
    name: "Проблема с электронной картой ДМС",
    nameKk: "ЕМС электронды картасының мәселесі",
    nameEn: "DMS e-card issue",
    domain: "health",
    category: "servicing",
    priority: "normal",
  },
  SC25: {
    id: "SC25",
    slug: "policy_validity",
    name: "Проверка действительности полиса",
    nameKk: "Полистің жарамдылығын тексеру",
    nameEn: "Check policy validity",
    domain: "general",
    category: "servicing",
    priority: "normal",
  },
  SC26: {
    id: "SC26",
    slug: "policy_documents_resend",
    name: "Повторная отправка документов",
    nameKk: "Полис құжаттарын қайта жіберу",
    nameEn: "Resend policy documents",
    domain: "general",
    category: "servicing",
    priority: "normal",
  },
  SC27: {
    id: "SC27",
    slug: "policy_renewal",
    name: "Продление полиса",
    nameKk: "Полисті ұзарту",
    nameEn: "Policy renewal",
    domain: "general",
    category: "sales",
    priority: "normal",
  },
  SC28: {
    id: "SC28",
    slug: "policy_cancel_refund",
    name: "Расторжение полиса и возврат средств",
    nameKk: "Полисті бұзу және қаражатты қайтару",
    nameEn: "Policy termination and refund",
    domain: "general",
    category: "servicing",
    priority: "normal",
  },
  SC29: {
    id: "SC29",
    slug: "contact_update",
    name: "Обновление контактных данных",
    nameKk: "Байланыс деректерін жаңарту",
    nameEn: "Update contact details",
    domain: "general",
    category: "servicing",
    priority: "normal",
  },
  SC30: {
    id: "SC30",
    slug: "payment_issue",
    name: "Оплата списана, но полис не оформлен",
    nameKk: "Төлем алынды, бірақ полис рәсімделмеді",
    nameEn: "Charged but policy not issued",
    domain: "general",
    category: "servicing",
    priority: "high",
  },
  SC31: {
    id: "SC31",
    slug: "payment_methods",
    name: "Способы оплаты и рассрочка",
    nameKk: "Төлем тәсілдері және бөліп төлеу",
    nameEn: "Payment methods and installments",
    domain: "general",
    category: "info",
    priority: "normal",
  },
  SC32: {
    id: "SC32",
    slug: "bonus_malus",
    name: "Класс бонус-малус и изменение цены",
    nameKk: "Бонус-малус класы және баға өзгеруі",
    nameEn: "Bonus-malus class and price change",
    domain: "auto",
    category: "info",
    priority: "normal",
  },
  SC33: {
    id: "SC33",
    slug: "offices",
    name: "Адреса и режим работы офисов",
    nameKk: "Кеңселер мекенжайы және жұмыс кестесі",
    nameEn: "Office addresses and hours",
    domain: "general",
    category: "info",
    priority: "normal",
  },
  SC34: {
    id: "SC34",
    slug: "app_help",
    name: "Помощь с приложением и аккаунтом",
    nameKk: "Қосымша және жеке кабинет көмегі",
    nameEn: "Mobile app and account help",
    domain: "general",
    category: "info",
    priority: "normal",
  },
  SC35: {
    id: "SC35",
    slug: "service_complaint",
    name: "Жалоба на обслуживание",
    nameKk: "Қызмет көрсетуге шағым",
    nameEn: "Service complaint",
    domain: "general",
    category: "feedback",
    priority: "high",
  },
  SC36: {
    id: "SC36",
    slug: "callback_request",
    name: "Заказ обратного звонка",
    nameKk: "Кері қоңырауға тапсырыс",
    nameEn: "Callback request",
    domain: "general",
    category: "contact",
    priority: "normal",
  },
  SC37: {
    id: "SC37",
    slug: "operator_request",
    name: "Запрос на соединение с оператором",
    nameKk: "Оператормен байланыстыру сұрауы",
    nameEn: "Request a human operator",
    domain: "general",
    category: "contact",
    priority: "normal",
  },
  SC38: {
    id: "SC38",
    slug: "fraud_report",
    name: "Подозрительный звонок / мошенничество",
    nameKk: "Күдікті қоңырау / алаяқтық хабарламасы",
    nameEn: "Suspicious call or fraud report",
    domain: "general",
    category: "security",
    priority: "urgent",
  },
  SC39: {
    id: "SC39",
    slug: "document_request",
    name: "Запрос справки или копии документа",
    nameKk: "Анықтама немесе құжат көшірмесін сұрау",
    nameEn: "Certificate or document copy request",
    domain: "general",
    category: "servicing",
    priority: "normal",
  },
  SC40: {
    id: "SC40",
    slug: "terms_explanation",
    name: "Разъяснение условий полиса",
    nameKk: "Полис талаптарын түсіндіру",
    nameEn: "Policy terms explanation",
    domain: "general",
    category: "info",
    priority: "normal",
  },
  SYS_OUT_OF_SCOPE: {
    id: "SYS_OUT_OF_SCOPE",
    slug: "out_of_scope",
    name: "Запрос вне сферы деятельности",
    nameKk: "Қызмет аясынан тыс сұрау",
    nameEn: "Out of scope request",
    domain: "system",
    category: "system",
    priority: "normal",
  },
  SYS_UNCLEAR: {
    id: "SYS_UNCLEAR",
    slug: "unclear",
    name: "Уточнение намерения",
    nameKk: "Мақсатты нақтылау",
    nameEn: "Unclear intent clarification",
    domain: "system",
    category: "system",
    priority: "normal",
  },
  SYS_GOODBYE: {
    id: "SYS_GOODBYE",
    slug: "goodbye",
    name: "Завершение разговора",
    nameKk: "Әңгімені аяқтау",
    nameEn: "Goodbye / session close",
    domain: "system",
    category: "system",
    priority: "normal",
  },
};

/**
 * Returns scenario metadata or a safe fallback object for unknown IDs.
 * @param {string|null|undefined} scenarioId
 * @param {'ru'|'kk'|'en'} [lang='ru']
 * @returns {{ id: string, name: string, category: string, priority: string, domain: string, slug: string }}
 */
export function getScenarioMeta(scenarioId, lang = "ru") {
  if (!scenarioId || typeof scenarioId !== "string") {
    return {
      id: scenarioId || "NONE",
      name: "Сценарий не выбран",
      category: "none",
      priority: "normal",
      domain: "none",
      slug: "none",
    };
  }

  const found = SCENARIO_CATALOG[scenarioId];
  if (found) {
    const localizedName = lang === "kk" ? found.nameKk : lang === "en" ? found.nameEn : found.name;
    return {
      ...found,
      name: localizedName,
    };
  }

  // Safe fallback for uncataloged IDs
  return {
    id: scenarioId,
    name: scenarioId,
    category: "custom",
    priority: "normal",
    domain: "custom",
    slug: scenarioId.toLowerCase(),
  };
}
